apiVersion: apps/v1
kind: Deployment
metadata:
  name: audioinspect
  labels:
    app: audioinspect
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: audioinspect
  template:
    metadata:
      labels:
        app: audioinspect
        tier: audioinspect
    spec:
      containers:
      - name: audioinspect
        image: haeji/audioinspect:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: audioinspect
---
apiVersion: v1
kind: Service
metadata:
  name: audioinspect
  labels:
    app: audioinspect
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: audioinspect
    tier: audioinspect
  type: LoadBalancer
